# Generated by Django 3.1.7 on 2022-08-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
